name: goreleaser

on:
  push:
    tags:
      - v*

env:
  dockerpushrm_version: "1.7.0"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Start Report
        uses: act10ns/slack@v2.0.0
        if: always()
        with:
          status: starting
          channel: '#github-actions'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TOKEN }}

      - name: Checkout
        id: checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Login DockerHub
        id: dockerLogin
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_BOT_USERNAME }}
          password: ${{ secrets.DOCKERHUB_BOT_TOKEN }}

      - name: Login Github Container Registry
        id: githubContainerRegistryLogin
        uses: docker/login-action@v1.10.0
        with:
          registry: "ghcr.io"
          username: "danopstech"
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        id: installGo
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Lint
        id: lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          skip-go-installation: true

      - name: Create Release
        id: createRelease
        uses: goreleaser/goreleaser-action@v2.7.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: push README to Dockerhub
        run: |
          wget https://github.com/christian-korneck/docker-pushrm/releases/download/v${dockerpushrm_version}/docker-pushrm_linux_amd64
          mkdir -p $HOME/.docker/cli-plugins/
          mv docker-pushrm_linux_amd64 $HOME/.docker/cli-plugins/docker-pushrm
          chmod +x $HOME/.docker/cli-plugins/docker-pushrm
          docker pushrm danopstech/starlink_exporter --file "./README.md" --short "${{ github.event.repository.description }}"

      - name: Slack Finish Report
        uses: act10ns/slack@v2.0.0
        if: always()
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#github-actions'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TOKEN }}
